region              = "{{.Var.region}}"
profile             = "{{.Var.profile}}"
aws_account_id      = "{{.Var.aws_account_id}}"
ssh_public_key_path = "{{.Var.sshPublicKeyPath}}"
environment         = "{{.Var.environment}}"
stack               = "{{.Var.stack}}"
network_cidr        = "{{.Var.networkCidr}}"
aws_account_id      = "{{.Var.awsAccountId}}"
