region              = "{{.Variables.region}}"
profile             = "{{.Variables.profile}}"
aws_account_id      = "{{.Variables.aws_account_id}}"
ssh_public_key_path = "{{.Variables.sshPublicKeyPath}}"
environment         = "{{.Variables.environment}}"
stack               = "{{.Variables.stack}}"
network_cidr        = "{{.Variables.networkCidr}}"
aws_account_id      = "{{.Variables.awsAccountId}}"
