db:
  hostname: FOO.TODO.us-east-1.rds.amazonaws.com
  health_check:
    port: 3306
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
drone:
  scale: 1
  health_check:
    port: 8000
    interval: 1000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: none
    response_timeout: 2000
    healthy_threshold: 2
