region              = "{{.Variables.region}}"
profile             = "{{.Variables.profile}}"
ssh_public_key_path = "{{.Variables.sshPublicKeyPath}}"
environment         = "{{.Variables.environment}}"
stack               = "{{.Variables.stack}}"
network_cidr        = "{{.Variables.networkCidr}}"
